spring.application.name=tsena-app

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/tsena}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:azerty}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET:d0dd8d94906180737f8d6d191c28268ba016efc354b328d0cb19893d4a5c7809}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
